Mt adatasource
2202-Fibonacci/colors pull request #18
Opened 2022-05-06 22:08 UTC by laurynnlowe

2022-05-06 22:36 UTC, mabastra approved these changes

2022-05-07 00:00 UTC, jennifermklein requested changes
can we undo the changes in the MTA folder files before merging?

2022-05-08 11:50 UTC, laurynnlowe commented
yes, no changes made to your files should have been permanent, just while I was testing

2022-05-08 12:03 UTC, jennifermklein commented on server/schema.graphql
> +    arrivalTimes(stationId: String, train: String, direction: String): String
we need to make these match the actual data types right? I'm happy to help with that.

2022-05-08 12:03 UTC, jennifermklein approved these changes

2022-05-08 12:04 UTC, merged